language: python
os: linux
dist: focal
stages:
  - test_3.6
  - test_3.7
  - test_3.8
  - test_pypy3
jobs:
  include:
    - stage: test_3.6
      language: python
      dist: focal
      python: 3.6
      install:
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
      - pip install .
      script:
      - pytest
      - black .
      after_success: coveralls
    - stage: test_3.7
      language: python
      dist: focal
      python: 3.7
      install:
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
      - pip install .
      script:
      - pytest
      - black .
      after_success: coveralls
    - stage: test_3.8
      language: python
      dist: focal
      python: 3.8
      install:
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
      - pip install .
      script:
      - pytest
      - black .
      after_success: coveralls
    - stage: test_pypy3
      language: python
      dist: focal
      python: pypy3
      install:
      - pip install -r requirements.txt
      - pip install -r requirements_dev_pypy.txt
      - pip install .
      script:
      - pytest
      after_success: coveralls
      deploy:
        provider: pypi
        username: __token__
        password: $PYPI_UPLOAD_TOKEN
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          tags: true
          branch: master
